
{
	"items": [
		{
			"axisY1": 10,
			"axisY2": 12,
			"axisX": "2013 Jan"
		}, {
			"axisY1": 10,
			"axisY2": 12,
			"axisX": "2013 Feb"
		}, {
			"axisY1": 10,
			"axisY2": 12,
			"axisX": "2013 Mar"
		}, {
			"axisY1": 10,
			"axisY2": 12,
			"axisX": "2013 Apr"
		}, {
			"axisY1": 10,
			"axisY2": 12,
			"axisX": "2013 May"
		}, {
			"axisY1": 10,
			"axisY2": 12,
			"axisX": "2013 Jun"
		}, {
			"axisY1": 10,
			"axisY2": 12,
			"axisX": "2013 July"
		}, {
			"axisY1": 10,
			"axisY2": 12,
			"axisX": "2013 Aug"
		}

	]
}


